FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

ARG APP_VERSION="api"
ENV APP_VERSION=$APP_VERSION

COPY . .

EXPOSE 80

CMD ["fastapi", "run", "app_api.py", "--host", "0.0.0.0", "--port", "80"]
